### ISSUE TITLE
Map to key + modifiers

### ISSUE THREAD

**Issue by karimknaebel** [zsugabubus/interception-k2k#10]
Is it possible to map for example caps+w to ctrl+w without remapping caps to ctrl for all keys?

**Comment by zsugabubus** [comment]
Is there any good reason to not to do that? I mean, if you will not press CapsLock with other keys simultaneously, does it count whether it is always Ctrl or not?

(Otherwise it may be possible with `struct multi_rule.{down,up}_press` but it requires slight coding since it currently makes possible mapping multiple keys only to a single key press.)

**Comment by karimknaebel** [comment]
Basically what I want to achieve is the following:

caps+h/j/k/l -> left/down/up/right
caps+b/w -> ctrl+b/w

caps+anything else -> I don't care

**Comment by karimknaebel** [comment]
So I got something working now, the first pipe maps caps to right ctrl, and the second pipe overwrite right ctrl + hjkl. It's fine because I'm never using right ctrl anyways.

```c
// interception-caps2rightctrl/tap-rules.h.in

{ .base_key = KEY_CAPSLOCK, .tap_key = KEY_ESC, .repeat_key = KEY_RIGHTCTRL, .hold_key = KEY_RIGHTCTRL, .hold_immediately = 1 },
```

```c
// interception-rightctrlhjkl2arrows/multi-rules.h.in

{ .keys = { KEY_RIGHTCTRL, KEY_H }, TO_KEY(KEY_LEFT),  DOWN_IFF_ALL_DOWN(2) },
{ .keys = { KEY_RIGHTCTRL, KEY_J }, TO_KEY(KEY_DOWN),  DOWN_IFF_ALL_DOWN(2) },
{ .keys = { KEY_RIGHTCTRL, KEY_K }, TO_KEY(KEY_UP),    DOWN_IFF_ALL_DOWN(2) },
{ .keys = { KEY_RIGHTCTRL, KEY_L }, TO_KEY(KEY_RIGHT), DOWN_IFF_ALL_DOWN(2) },
```

**Comment by zsugabubus** [comment]
Great!
