### ISSUE TITLE
changing key up/down order for tapping

### ISSUE THREAD

**Issue by brabalan** [zsugabubus/interception-k2k#2]
I have a keyboard where the right control key is at the position of the `'` key (to the right of the `;` key), so I configured it this way:

``` c
{ .base_key = KEY_RIGHTCTRL, .tap_key = KEY_APOSTROPHE, .repeat_key = KEY_RIGHTCTRL, .hold_key = KEY_RIGHTCTRL },
```

It works great, but when I type too fast, I get a `CTRL-a` instead of a `'a`. I think the problem is that I do this: `CTRL` down, `a` down, `CTRL` up, `a` up (I don't think it's a question of delay). Is it possible in that case to generate the tap event?

By the way, what is the difference between `repeat_key` and `hold_key`? I tried setting `hold_key` to apostrophe, and now getting the `CTRL` key to work as `CTRL` requires waiting quite a while. I while try using shorter repeat settings to see if that helps.

**Comment by zsugabubus** [comment]
It sometimes also occurs to me (with `Space -> Meta`) but how should the program know whether you want `Ctrl-a` or `'a` if you press the keys simultaneously? Your reasoning about key events is correct and it's the expected behavior, but here are two things you can try:
* With a little practice you could try teaching your muscles to release `Ctrl` before you press `A`.
* Try setting `repeat_key = KEY_APOSTROPHE`. It will work as long as there is a short delay (one key repeat) between pressing `Ctrl` and pressing `A` down.
```
{ .base_key = KEY_RIGHTCTRL, .tap_key = KEY_APOSTROPHE, .repeat_key = KEY_APOSTROPHE, .hold_key = KEY_RIGHTCTRL }
```

> By the way, what is the difference between repeat_key and hold_key?

https://github.com/zsugabubus/interception-k2k/blob/b0bfc826e297eebfa30a0fae541a5f0a46d43237/k2k.c#L114-L117

When you press `base_key` down, program have to decide how it should act in the future, so it ignores every event originating from `base_key` until not decided:

1. If `base_key` repeated: When `repeat_delay` reaches zero act as `repeat_key`. Default is `0` so it will act as `repeat_key` starting from the first `base_key` repeating.)  If still not zero ignore the repeat event, because we still don't know how it should act. I proposed you to do this, because if you press `R_Ctrl`, it will automagically generate `'` after some time.
2. If other key down: Act as `hold_key`, because you hold this key with others.
3. Otherwise: Do nothing, still couldn't decide.

`base_key` released: If it has been decided how it should act release that key, otherwise send `tap_key` press and release events.

If you still need more explaining run `make test` (should output some debug information), and/or `evtest` to view all events.

**Comment by brabalan** [comment]
This is great information, thanks. I'm going to play with `repeat_delay`. What is the default value, and is it in milliseconds?

**Comment by zsugabubus** [comment]
`repeat_delay` is expressed in the term of received repeat event count. (How many repeat events we should wait for before acting as `repeat_key`?) Timings depends on your keyboard (settings), in my case it's ~15 ms.

```
$ evtest
# A key down
Event: time 1571330643.291462, type 1 (EV_KEY), code 30 (KEY_A), value 1
Event: time 1571330643.291462, -------------- SYN_REPORT ------------
# First repeat event received. `repeat_delay=0` would mean that this A would be an apostroph for example.
Event: time 1571330643.540231, type 1 (EV_KEY), code 30 (KEY_A), value 2
Event: time 1571330643.540231, -------------- SYN_REPORT ------------
# `repeat_delay=1` means that we wait for one repeat event for arriving  (that we ignore of course so applications doesn't receive it) and at following repeat we change it to an apostroph.
Event: time 1571330643.555900, type 1 (EV_KEY), code 30 (KEY_A), value 2
Event: time 1571330643.555900, -------------- SYN_REPORT ------------
Event: time 1571330643.569048, type 1 (EV_KEY), code 30 (KEY_A), value 2
Event: time 1571330643.569048, -------------- SYN_REPORT ------------
Event: time 1571330643.592557, type 1 (EV_KEY), code 30 (KEY_A), value 2
Event: time 1571330643.592557, -------------- SYN_REPORT ------------
Event: time 1571330643.598945, type 1 (EV_KEY), code 30 (KEY_A), value 2
Event: time 1571330643.598945, -------------- SYN_REPORT ------------
# A key up
Event: time 1571330643.608888, type 1 (EV_KEY), code 30 (KEY_A), value 0
```

Every unset field is initialized with `0`, it's C specific.

**Comment by brabalan** [comment]
Thanks again. I'm playing with the values and a `repeat_delay` of 10 seems nice. (The default value of 0 is a bit short for me.)

**Comment by zsugabubus** [comment]
I've just now implemented `tap_typing` that you can set (`=1`) for tap rules. It basically tries to filter out these undesired tappings. So if you still experience some issues around it, you may be interested in the update. (Otherwise don't update if it works perfectly.)

**Comment by brabalan** [comment]
Thanks, I'll give it a try
